### ISSUE TITLE
Densities?

### ISSUE THREAD

**Issue by srush** [XzwHan/CARD#11]
Thank you for the clear and interesting paper, and codebase. 

I had a somewhat basic question. Is it possible in the code base to estimate a density p(y | x)? The code make is clear how to sample a y_0 , but I couldn't tell if there were methods for getting the density directly from example y's.

**Comment by XzwHan** [comment]
Hi @srush, thank you for checking out our work.

We don't make any assumptions to the parametric form for the distribution $p(\boldsymbol{y}\ |\ \boldsymbol{x})$, thus as you mentioned we would only obtain $\boldsymbol{y}_0$ samples given the same covariates input $\boldsymbol{x}=x$ during inference.

Meanwhile, in our work, we do provide density calculation via the predictive NLL metric, mainly for the purpose of contextualizing our work with existing models. Therefore, we follow their assumption in the distributional form of $p(\boldsymbol{y}\ |\ \boldsymbol{x})$:

* For regression, our baseline models are BNN methods, and their framework usually renders $p(\boldsymbol{y}\ |\ \boldsymbol{x})$ to be Gaussian (see our discussion in Section A.18). The density is thus computed as Gaussian NLL on the test set: the NLL metrics reported in the paper were computed via function `compute_batch_NLL` [here](https://github.com/XzwHan/CARD/blob/f438209cc3212aed65594e4c4818cac05183eef4/regression/card_regression.py#L866), which was adapted from [this](https://github.com/yaringal/DropoutUncertaintyExps/blob/master/net/net.py#L133) implementation in the official MC Dropout repo. The formula of the predictive NLL is as follows:
    $$\text{NLL} = -\frac{1}{n}\sum_{i=1}^n\log\Big(\frac{1}{k}\sum_{j=1}^k\mathcal{N}\big(y_i\ |\ \hat{y}_{i,j}, \hat{\sigma}_i\big)\Big),$$
    in which $n$ is the batch size of the test set, $k$ is the number of $\boldsymbol{y}\_0$ samples given each test covariates input $\boldsymbol{x}\_i$, $\hat{y}\_{i,j}$ is one of the $k$ $\boldsymbol{y}\_0$ samples, $\hat{\sigma}\_i$ is the unbiased estimation of variance with all $k$ $\boldsymbol{y}\_0$ samples, and $\mathcal{N}\big(y_i\ |\ \hat{y}\_{i,j}, \hat{\sigma}\_i\big)$ is the Gaussian density with mean $\hat{y}\_{i,j}$ and variance $\hat{\sigma}\_i$ of true $y_i$.
    
    Note that although we did not explicitly apply any non-parametric density estimation techniques like KDE in our work, you might find the expression in the $\log$ very similar to a kernel density estimator with a Gaussian kernel &mdash; the main difference is that we use the empirical variance instead of $1$ for the variance parameter.

* For classification, the NLL metric is computed based on the assumption of a categorical distribution for the labels, and is directly computed [here](https://github.com/XzwHan/CARD/blob/f438209cc3212aed65594e4c4818cac05183eef4/classification/card_classification.py#L1097) in our code. Unlike the procedure in regression, our NLL computation for classification is the same as that of a deterministic classifier that outputs a probability vector as a point estimate, rather than taking advantage of the stochastic outputs of probability vectors (thus a more coarse version of NLL when compared to the regression case): we would first obtain the point estimate of the probability vector by taking the mean across all samples (check Line 569 `gen_y_all_class_mean_prob = gen_y_all_class_probs.mean(1)`), and use that along with true labels to compute the predictive NLL.

**Comment by srush** [comment]
Thanks for the detailed answer. I'm still a bit confused though on your recommendation. As a practitioner, I would like to use diffusion for non-parametric high-dimensional regression without making Normal assumptions. Your method seems to work great. However I need to be able to compare densities of points ( in a somewhat efficient manner). What would you recommend I do? Should I try to compute individual elbos? Should I just look to other methods?

**Comment by XzwHan** [comment]
We've proposed Quantile Interval Coverage Error (QICE) as a metric to compare true and generated distributions without making any assumptions to the parametric form of $p(\boldsymbol{y}\ |\ \boldsymbol{x})$ &mdash; the writing is in Section 4.1.1 of our paper, and the implementation is via function `compute_true_coverage_by_gen_QI` [here](https://github.com/XzwHan/CARD/blob/main/regression/card_regression.py#L786).

We've observed that our model performance is more amplified via QICE on datasets with larger number of instances ($e.g.$, the **Naval**, **Protein**, **Year** datasets in Table 3), perhaps because having more true datapoints allows for better representation of the true distribution. I'm not sure if the computation of QICE is efficient, as it requires a sufficient amount of $\boldsymbol{y}_0$ samples to compute the quantile boundaries accurately (we usually use $1000$ samples for the cases where the number of quantile intervals is set to $10$).

**Comment by srush** [comment]
I see. So I guess the answer to my question is no. Okay, I'll check out other methods. Cool work though!

**Comment by XzwHan** [comment]
I think it depends on the actual dataset performance-wise &mdash; what CARD can offer is a model for high dimensional regression without any parametric assumptions to $p(\boldsymbol{y}\ |\ \boldsymbol{x})$, and a metric that empirically compares true and learned distributions without parametric assumptions either.

Thank you for the questions &mdash; best of luck on your project!
